---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapi
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: weatherapi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: weatherapi
    spec:
      containers:
      - name: weatherapi
        image: weatherapi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: weatherapi-env
      terminationGracePeriodSeconds: 180