resources:
- deployment.yml
- service.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: frontend-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
    - GRAFANA_URL=grafana:3000
    - services__weatherapi__0=http://weatherapi:8080
    - services__weatherapi__1=https://weatherapi:8443
    - ASPNETCORE_URLS=http://+:8080

secretGenerator:
- name: frontend-secrets
  envs:
  - .frontend.secrets
